In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
arr_1d

array([1, 2, 3, 4])

In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
# ndim use of find the dimension array
arr_1d.ndim

1

In [5]:
arr_2d = np.array([[1, 2, 3, 4],[11, 22, 33, 44],[111, 222, 333, 4444]])
arr_2d

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333, 4444]])

In [6]:
arr_md = np.array([[[1, 2, 3, 4],[11, 22, 33, 44],[111, 222, 333, 4444],[22,33,44,55]],[[12,13,14,15],[22,23,24,25],[1,1,1,1],[2,2,2,2]]])
arr_md

array([[[   1,    2,    3,    4],
        [  11,   22,   33,   44],
        [ 111,  222,  333, 4444],
        [  22,   33,   44,   55]],

       [[  12,   13,   14,   15],
        [  22,   23,   24,   25],
        [   1,    1,    1,    1],
        [   2,    2,    2,    2]]])

In [7]:
arr_md.ndim

3

In [8]:
arr_1d.size

4

In [9]:
arr_2d.size

12

In [10]:
arr_md.size

32

In [11]:
arr_1d.shape

(4,)

In [12]:
arr_2d.shape

(3, 4)

In [13]:
arr_md.shape

(2, 4, 4)

In [14]:
arr_1d.dtype

dtype('int64')

In [15]:
arr_2d.dtype

dtype('int64')

In [16]:
arr_md.dtype

dtype('int64')

In [18]:
#1 methods
max_1s=np.array([[1,1,1,1],[1,1,1,1], [1,1,1,1]])
max_1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
#2 method predefine function ones(column)
max_1one=np.ones(5)
max_1one

array([1., 1., 1., 1., 1.])

In [20]:
max_on = np.ones((3,4))
max_on

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
max_1s = np.ones((3,4), dtype=int)
max_1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
max_0s = np.zeros((3,4))
max_0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
max_os = np.zeros((3,4), dtype=bool)
max_os

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
max_os = np.zeros((3,4), dtype=str)
max_os

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [25]:
em_str = ''
bool(em_str)

False

In [26]:
em_mx = np.empty((3,3))
em_mx

array([[4.69639305e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [27]:
# NUMPY FUNCTIONS

In [28]:
ar_1d = np.arange(1,13)
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
even_1d = np.arange(1,13,2)
even_1d

array([ 1,  3,  5,  7,  9, 11])

In [30]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [31]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [34]:
ar_1d = np.arange(1,13)
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a_2d = ar_1d.reshape(3,4)
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a_3d = ar_1d.reshape(2,3,2)
a_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [37]:
ar = np.arange(0,20).reshape(4,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
ar.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
ar.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
ar.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [43]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
print(arr1+arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [45]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [47]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [48]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [49]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [50]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [53]:
arr1.max()

9

In [54]:
arr1.argmax()

8

In [55]:
arr1.max(axis=0)

array([7, 8, 9])

In [56]:
arr1.max(axis=1)

array([3, 6, 9])

In [57]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2.min()

1

In [59]:
arr2.argmin()

0

In [60]:
arr2.max(axis=0)

array([7, 8, 9])

In [61]:
arr2.max(axis=1)

array([3, 6, 9])

In [62]:
np.sum(arr1)

45

In [63]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [64]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [65]:
np.mean(arr1)

5.0

In [66]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [67]:
# std-> standard Deviation
np.std(arr1)

2.581988897471611

In [68]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [69]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [70]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [71]:
mx=np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
mx[0, 0]

1

In [73]:
mx[4, 5]

46

In [74]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [75]:
mx[:,2:5]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85],
       [93, 94, 95]])

In [76]:
mx[2:4, 2:4]

array([[23, 24],
       [33, 34]])

In [77]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [78]:
mx[:,0:1].ndim

2

In [79]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [80]:
mx[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [81]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [82]:
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [84]:
mx.itemsize

8

In [85]:
# numpy concatination and split
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
arr2=np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [88]:
l1=[1,2,3]
l2=[4,5,7]
l1+l2

[1, 2, 3, 4, 5, 7]

In [89]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [90]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [91]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [92]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [93]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [94]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [95]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [96]:
d1=np.split(arr1,2)
type(d1)

list

In [97]:
type(d1[0])

numpy.ndarray

In [98]:
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [99]:
d1 = np.array([4,7,1,3,9])
np.split(d1,[1,3])

[array([4]), array([7, 1]), array([3, 9])]

In [100]:
import matplotlib.pyplot as plt

In [101]:
np.sin(180)

-0.8011526357338304

In [102]:
np.sin(90)

0.8939966636005579

In [103]:
# Pandas

In [104]:
import pandas as pd
list_1 = [1,2,3,4,5,6,'kapil']
list_1

[1, 2, 3, 4, 5, 6, 'kapil']

In [105]:
series1 = pd.Series(list_1)
series1

0        1
1        2
2        3
3        4
4        5
5        6
6    kapil
dtype: object

In [106]:
type(series1)

pandas.core.series.Series

In [107]:
series2=pd.Series([1,2,3,4,5])
series2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [108]:
empty_s = pd.Series([])
empty_s

Series([], dtype: object)

In [109]:
series3 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
series3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [110]:
series3 = pd.Series([1,2,3,4,5], index={'a','b','c','d','e'}, dtype=float)
series3

c    1.0
d    2.0
b    3.0
e    4.0
a    5.0
dtype: float64

In [111]:
series3 = pd.Series([1,2,3,4,5], index={'a','b','c','d','e'}, dtype=float, name='data value')
series3

c    1.0
d    2.0
b    3.0
e    4.0
a    5.0
Name: data value, dtype: float64

In [112]:
scalar_s = pd.Series(0.5, index=[1, 2, 3])
scalar_s

1    0.5
2    0.5
3    0.5
dtype: float64

In [113]:
scalar_s = pd.Series({'a':1, 'b':2})
scalar_s

a    1
b    2
dtype: int64

In [114]:
series3=pd.Series([1,2,3,4,5])
series3

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [115]:
series3[0]

1

In [117]:
series3[0:3]

0    1
1    2
2    3
dtype: int64

In [118]:
series3[0:3:2]

0    1
2    3
dtype: int64

In [119]:
max(series3)

5

In [120]:
min(series3)

1

In [122]:
s3=pd.Series([1,2,3,4,5])
s3

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [123]:
s3[s3>3]

3    4
4    5
dtype: int64

In [125]:
s4 = pd.Series([1,2,3,4,5])
s4

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [126]:
s3+s4

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [127]:
s5=pd.Series([1,2,3,4,5,6])
s5

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [128]:
s4+s5

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
5     NaN
dtype: float64