In [1]:
import statistics as st 
a=[20, 10, 50, 10, 21, 90] 
s=st.mode(a) 
print("Mode:",s) 

Mode: 10


In [2]:
a=[20, 10, 50, 10, 21, 90] 
m=st.mean(a) 
print("Mean:",m) 

Mean: 33.5


In [3]:
import numpy as np 
b=np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6]]) 
print(b) 
print("Dim:",b.ndim) 

[[10 20 30 50 10]
 [ 1  2  3  5  6]]
Dim: 2


In [4]:
b=np.array([[10, 20, 30, 50, 10],[1, 2, 3, 5, 6],[1,1,1,1,1]]) 
print(b) 
print("Dim:",b.ndim) 
print("Shape:",b.shape) 
print("Size:",b.size) 
print("Item Size:",b.itemsize) 
print("Data type:",b.dtype) 

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
Dim: 2
Shape: (3, 5)
Size: 15
Item Size: 8
Data type: int64


In [7]:
c=np.empty((5,5))
c

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37960147e-306, 1.33511562e-306,
        2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 7.56602523e-307],
       [8.90095411e-307, 1.42419530e-306, 2.22522596e-306,
        2.22507386e-306, 3.91786943e-317]])

In [8]:
d=np.arange(0,100,2)
d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
e=np.reshape(d,(10,5))
e

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [10]:
f=np.reshape(e,(2,5,5)) 
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [11]:
print("Last element:",d[10]) 
 
print("ELement upto 10:",d[:10])

Last element: 20
ELement upto 10: [ 0  2  4  6  8 10 12 14 16 18]


In [12]:
print("Last 5 element:",d[-5:])

Last 5 element: [90 92 94 96 98]


In [13]:
print("Alternative Numbers:",d[::2])

Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [15]:
import pandas as pd 

p_dict = {
    'pid': [1, 2, 3, 4, 5], 
    'pname': ['A', 'B', 'C', 'D', 'E'], 
    'price': [10, 20, 30, 40, 50], 
    'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']
}

# Creating DataFrame
grt = pd.DataFrame(p_dict)
print(grt)


   pid pname  price vendor
0    1     A     10     V1
1    2     B     20     V2
2    3     C     30     V3
3    4     D     40     V4
4    5     E     50     V5
